Routes:
- Path : "/api/v1/role"
  Callback : "GetRole"
  Method : "GET"
  Authorization : "NO" 
- Path : "/api/v1/getProjectManagerSearchResult/{id}"
  Callback : "GetProjectManagerSearchResult"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/getProjectName"
  Callback : "GetProjectName"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/getProjectData"
  Callback : "GetData"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/getOpenPositionByAging"
  Callback : "GetOpenPositionByAging"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/Profile"
  Callback : "ChangeProfileImage"
  Method : "POST"
  Authorization : "YES"
- Path : "/api/v1/Profile"
  Callback : "FileServe"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/signin"
  Callback : "SignIn"
  Method : "POST"
  Authorization : "NO"
- Path : "/api/v1/refresh"
  Callback : "Refresh"
  Method : "POST"
  Authorization : "NO"
- Path : "/api/v1/actionitems"
  Callback : "ActionItemPostData"
  Method : "POST"
  Authorization : "YES"
- Path : "/api/v1/actionitems"
  Callback : "ActionItemUpdateData"
  Method : "PUT"
  Authorization : "YES"
- Path : "/api/v1/actionitems"
  Callback : "ActionItemDeleteData"
  Method : "DELETE"
  Authorization : "YES"
- Path : "/api/v1/actionitems"
  Callback : "ActionItemGetData"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/actionitems/{id}"
  Callback : "ActionItemGetDataID"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/projectupdates"
  Callback : "ProjectUpdatesGetData"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/projectupdates"
  Callback : "ProjectUpdatesCreateData"
  Method : "POST"
  Authorization : "YES"
- Path : "/api/v1/projectupdates/{id}"
  Callback : "ProjectUpdatesGetDataID"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/projectupdates"
  Callback : "ProjectUpdatesUpdateData"
  Method : "PUT"
  Authorization : "YES"
- Path : "/api/v1/projectupdates"
  Callback : "ProjectUpdatesDeleteData"
  Method : "DELETE"
  Authorization : "YES"
- Path : "/api/v1/updateprospects"
  Callback : "UpdateProspectGetData"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/updateprospects"
  Callback : "UpdateProspectCreateData"
  Method : "POST"
  Authorization : "YES"
- Path : "/api/v1/updateprospects/{id}"
  Callback : "UpdateProspectGetDataID"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/updateprospects"
  Callback : "UpdateProspectUpdateData"
  Method : "PUT"
  Authorization : "YES"
- Path : "/api/v1/updateprospects"
  Callback : "UpdateProspectDeleteData"
  Method : "DELETE"
  Authorization : "YES"
- Path : "/api/v1/actionitemoverview"
  Callback : "ActionItemGetOverview"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/actionitemoverview/saydo"
  Callback : "ActionItemGetSayDo"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/actionitemoverview/saydotrend"
  Callback : "ActionItemGetTrend"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/activeresignations"   #merge set 1
  Callback : "GetAllresignations" 
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/activeresignations"    
  Callback : "CreateResignations"
  Method : "POST"
  Authorization : "YES"
- Path : "/api/v1/activeresignations/{emp_name}"   # merge set 1
  Callback : "GetResignationsbyName"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/activeresignations"
  Callback : "DeleteResignations"
  Method : "DELETE"
  Authorization : "YES"
- Path : "/api/v1/activeresignations"
  Callback : "UpdateResignations"
  Method : "PUT"
  Authorization : "YES"
- Path : "/api/v1/activeheadcount"    #seprate program and project manager using query
  Callback : "Getactiveheadcount"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/projectheadcount"   #seprate program and project manager using query
  Callback : "Getprojectheadcount"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/headcount"    #merge set 2
  Callback : "Getallheadcount"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/headcount"
  Callback : "Createheadcount"
  Method : "POST"
  Authorization : "YES"
- Path : "/api/v1/headcount/{projects.project_name}"    #merge set 2
  Callback : "Getheadcountbyname"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/headcount"
  Callback : "Deleteheadcount"
  Method : "DELETE"
  Authorization : "YES"
- Path : "/api/v1/headcount"
  Callback : "Updateheadcount"
  Method : "PUT"
  Authorization : "YES"
- Path : "/api/v1/resignationsdetails"    #seprate program and project manager using query
  Callback : "Getcompleteresignations"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/toberetained"       #merge set 3
  Callback : "Getalltoberetained"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/toberetained"
  Callback : "Createtoberetained"
  Method : "POST"
  Authorization : "YES"
- Path : "/api/v1/toberetained/{projects.project_name}"     #merge set 3
  Callback : "Gettoberetainedbyprojectname"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/toberetained"
  Callback : "Deletetoberetained"
  Method : "DELETE"
  Authorization : "YES"
- Path : "/api/v1/toberetained"
  Callback : "Updatetoberetained"
  Method : "PUT"
  Authorization : "YES"
- Path : "/api/v1/retention"      #merge set4
  Callback : "Getallretentions"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/retention"
  Callback : "Createretentions"
  Method : "POST"
  Authorization : "YES"
- Path : "/api/v1/retention/{projects.project_name}"      #merge set4
  Callback : "Getretentionbyprojectname"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/retention"
  Callback : "Deleteretentions"
  Method : "DELETE"
  Authorization : "YES"
- Path : "/api/v1/retention"
  Callback : "Updateretentions"
  Method : "PUT"
  Authorization : "YES"
- Path: "/api/v1/openpositions"
  Callback: "Getallopenpositions"
  Method: "GET"
  Authorization : "YES"
- Path: "/api/v1/openpositions/{id}"
  Callback: "Getopenpositions"
  Method: "GET"
  Authorization : "YES"
- Path: "/api/v1/openpositions"
  Callback: "Createopenpositions"
  Method: "POST"
  Authorization : "YES"
- Path: "/api/v1/openpositions"
  Callback: "Updateopenpositions"
  Method: "PUT"
  Authorization : "YES"
- Path: "/api/v1/openpositions"
  Callback: "Deleteopenpositions"
  Method: "DELETE"
  Authorization : "YES"
- Path: "/api/v1/openpositions/upload"
  Callback: "Putallopenpositions"
  Method: "POST"
  Authorization : "YES"
