Routes:
- Path : "/api/v1/putProjectData"
  Callback : "Putdata"
  Method : "POST"
  Authorization : "YES"
- Path : "/api/v1/getProjectDataByManagerName/{id}"
  Callback : "GetdataByManager"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/getProjectDataByProjectName/{id}"
  Callback : "GetdataByProject"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/getProjectName"
  Callback : "GetProjectName"
  Method : ""
  Authorization : "YES"
- Path : "/api/v1/updateProject"
  Callback : "UpdateData"
  Method : "PUT"
  Authorization : "YES"
- Path : "/api/v1/deleteProject"
  Callback : "DeleteData"
  Method : "PUT"
  Authorization : "YES"
- Path : "/api/v1/getProjectData"
  Callback : "GetData"
  Method : "GET"
  Authorization : "YES"
- Path : "/api/v1/getOpenPositionByAging"
  Callback : "GetOpenPositionByAging"
  Method : ""
  Authorization : "YES"
